//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::archive_rule::Entity as ArchiveRule;
pub use super::request::Entity as Request;
pub use super::request_schedule::Entity as RequestSchedule;
pub use super::task::Entity as Task;
pub use super::user::Entity as User;
